{
 "title": "Ping Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_system{cpu!=\"cpu-total\"}*100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}*100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mem_used" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_average_response_ms", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "CPU/Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}*100",
     "legendFormat": "cpu"
    },
    { "expr": "mem_used", "legendFormat": "mem" }
   ]
  },
  {
   "title": "Ping Average response Time",
   "type": "graph",
   "description": "test",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "ping_average_response_ms", "legendFormat": "{{environment}}_{{url}}" }
   ]
  },
  {
   "title": "Ping Response Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping_average_response_ms" },
    { "expr": "ping_maximum_response_ms" },
    { "expr": "ping_minimum_response_ms" }
   ]
  }
 ]
}